name: Deploy Guia Chapada

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build frontend cliente
        run: |
          cd frontend/cliente
          npm install
          npm run build

      - name: Build frontend admin
        run: |
          cd frontend/admin
          npm install
          npm run build
